<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    <title>FizzBuzz</title>
    <!-- Twitter Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/"><em>Fizz</em><strong>Buzz</strong></a>
            </div>
<?php
/** This feels a little wrong, but since we're not in a full MVC... */
$sr = new \FizzBuzz\Service\SectionsRepository();
foreach ($sr->findAll() as $s)
{
?>
            <ul class="nav navbar-nav">
                <li><a href="/section/<?php echo $s['slug'] ?>"><?php echo $s['title']; ?></a></li>
            </ul>
<?php
}
?>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/phpinfo">phpinfo</a></li>
            </ul>
        </div>
    </nav>
