<?php include __DIR__.'/../inc/header.phtml'; ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <h1><?= ucfirst(htmlentities($this->article['title'])) ?></h1>
            <hr>
            <?= $this->article['body'] ?>
            <hr>
        </div>
    </div>
</div>

<script>
    // Replace request path if it's different to the expected one
    if (window.location.pathname !== '<?= $this->requestPath ?>') {
        window.history.replaceState({}, 'FizzBuzz', '<?= $this->requestPath ?>');
    }
</script>

<?php include __DIR__.'/../inc/footer.phtml'; ?>
